
export const DRINK_SEARCH_VALUE_UPDATE = 'DRINK-SEARCH-VALUE-UPDATE';
export const SET_DRINKS = 'SET-DRINKS';
export const SELECT_DRINK = 'SELECT-DRINK';
export const UPDATE_INGREDIENT_FIELD = 'UPDATE-INGREDIENT-FIELD';
export const FILTER_BY_INGREDIENT = 'FILTER-BY-INGREDIENT';
export const SELECT_CATEGORY = 'SELECT-CATEGORY';
export const SELECT_SORT = 'SELECT-SORT';
